//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankTransactionAPIDemo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://integration.simplifi.solutions:8080/api")]
        public string BankStatementsURL {
            get {
                return ((string)(this["BankStatementsURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoLogin {
            get {
                return ((bool)(this["AutoLogin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hubino-india")]
        public string UserName {
            get {
                return ((string)(this["UserName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hubino@123")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://integration.simplifi.solutions:8080/api")]
        public string SecurityURL {
            get {
                return ((string)(this["SecurityURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowErrorMessageDetail {
            get {
                return ((bool)(this["ShowErrorMessageDetail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<!DOCTYPE html>
<html lang=""en"">
<head>
    <meta charset=""UTF-8"">
    <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"">
    <title>BankLogin</title>
    <meta name=""viewport"" content=""width=device-width, initial-scale=1"">
    <link rel=""icon"" type=""image/x-icon"" href=""favicon.ico"">
    <link rel=""stylesheet"" href=""css/styles.css"">
</head>
<body>
    <bank-login
      jwt-token=""Bearer param1"">
    </bank-login>
    <script type=""text/javascript"" src=""https://integration.simplifi.solutions/bankstatements/pages/bank-login-component/js/bank-login-es2015.js""></script>
</body>
</html>
")]
        public string HTMLTemplate {
            get {
                return ((string)(this["HTMLTemplate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<script type='text/javascript' src='https://cdn.yodlee.com/fastlink/v3/initialize.js'></script>
<body>

<div id=""container-fastlink"">
	<div style=""text-align: center;"">
   <input type=""submit"" id=""btn-fastlink"" value=""Link an Account"">
</div>
</div>

<script>
	(function (window) {
					//Open FastLink
					var fastlinkBtn = document.getElementById('btn-fastlink');
					fastlinkBtn.addEventListener('click', function () {
							window.fastlink.open({
									fastLinkURL: 'param1',
									accessToken: 'Bearer param2',
									params: {
									              userExperienceFlow : 'Aggregation'
                                    },
									onSuccess: function (data) {
											console.log(data);
									},
									onError: function (data) {
											console.log(data);
									},
									onExit: function (data) {
											console.log(data);
									},
									onEvent: function (data) {
											console.log(data);
									}
							}, 'container-fastlink');
					}, false);
			}(window));
	</script>
</body>")]
        public string JSTemplate {
            get {
                return ((string)(this["JSTemplate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveJSON {
            get {
                return ((bool)(this["SaveJSON"]));
            }
        }
    }
}
